package core

const ATTR_SOLID = "SOLID;"
const ATTR_FIGHTABLE = "FIGHTABLE;"
const ATTR_FOREGROUND = "FORGROUND;"
const ATTR_CLIMBABLE = "CLIMABLE;"
const ATTR_EQUIPTABLE = "EQUIPTABLE;"
const ATTR_USABLE = "USEABLE;"
const ATTR_SPELL = "SPELL;"
const ATTR_BOSS = "BOSS;"